language: bash

matrix:
  include:
    - os: linux
      env: TARGET=android_armv7
    - os: linux
      env: TARGET=android_arm64
    - os: linux
      env: TARGET=android_x86
    - os: linux
      env: TARGET=android_x64
    - os: osx
      osx_image: xcode9.4
      env: TARGET=ios
    - os: osx
      osx_image: xcode8.3
      env: TARGET=macos
    - os: windows
      env: TARGET=win64

before_script:
- |
  if [[ $TARGET =~ ^android ]]; then
      pushd "$HOME" >/dev/null
      if [[ ! -e "android-ndk-r16b/source.properties" ]]; then
          curl --retry 10 -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
          unzip -oq android-ndk-r16b-linux-x86_64.zip
          rm android-ndk-r16b-linux-x86_64.zip
      fi
      popd >/dev/null
      export ANDROID_NDK_r16b="$HOME/android-ndk-r16b"
  fi

script:
  - OPUSBUILD_BUILD_DIR=$PWD/build_static bash -x ./build.sh $TARGET static lib_static
  - OPUSBUILD_BUILD_DIR=$PWD/build_shared bash -x ./build.sh $TARGET shared lib_shared

before_deploy:
  - mkdir -p "binaries-${TARGET}-${TRAVIS_TAG}"
  - cp "libopus/COPYING" "binaries-${TARGET}-${TRAVIS_TAG}"
  - mv lib_static "binaries-${TARGET}-${TRAVIS_TAG}/static"
  - mv lib_shared "binaries-${TARGET}-${TRAVIS_TAG}/shared"
  - |
    if type zip >/dev/null 2>/dev/null; then
        zip "binaries-${TARGET}-${TRAVIS_TAG}.zip" -r "binaries-${TARGET}-${TRAVIS_TAG}"
    elif type 7z >/dev/null 2>/dev/null; then
        7z a -r "binaries-${TARGET}-${TRAVIS_TAG}.zip" "binaries-${TARGET}-${TRAVIS_TAG}"
    else
        echo 'Zip archiver not found.'
        exit 1
    fi

deploy:
  provider: releases
  api_key:
    secure: secure: "aoaeC+1zIEL7jzPz56C9aN/79+I8cwLgpqSNJopwxBXoJL4DLGHc15PRxRUyCZIU/LvORH8HVJsdjeGcivGhKcwwmyN+NG9hkHzOt1ZjTGiBw0KRGS3aAlWQOPwTJKHAbcjmSph6+LE/00NjBi8kaFNAw9jvXD8ZwFtQTuJySO9JKpN7ncA+lu5X1OCk6LS5PcFXc9DbtP/uAQoeohGQzEOdmhgUpwF/BX5rRtch2NqZyEkkHiMoGzLisMqb4hXA3psaXnN+IYyBcAsdZkC2jsN3irfpSo52wvp7uADuMIaYWqVIdN2QN4vy2yd03FzCliR+n7xm2SMiT+4cLcpAYPa4k5ISXjgA0Km9Z7ndn08fqg0o9d+kyTnSioxu/bSFT7HTZGPc+HFG04UGc/TvS/dauka/Iqyjmf9jCJ+2FZYGeoxJRmXdqYly+KWFqeD2vtYE0FGQNYeTfNgXpcVqN/9NlGjngmMZmJo0C8pNhvltFaV41XJEpETrCh7J15wEFClutemYumVo5KXpxaWQMhIWTB/WZGKwTFjyf/TOa1BC78MvS4YrRlr2RqTgLZkID4CUndvCRtND6p2g35kfp9dCvJh2BDy32co2ir2CJWKElXhr289NYcloBrRKtO9VAdpbkwu2bLyuPzsyo1qAN1gbV43snLV237+eEPCcSi4="
  file: binaries-${TARGET}-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
